import { jsPDF } from 'jspdf';
import { Analysis, Scan } from '@/lib/types/database';

/**
 * Generate a PDF report blob for a scan analysis
 * Creates a 4-page professional medical document with:
 * Page 1: Summary (classification, risk score, AI summary, disclaimer)
 * Page 2: Detailed Findings (radiomic features, areas of concern, measurements)
 * Page 3: Longitudinal Comparison (if applicable)
 * Page 4: Clinical Context and Recommendations
 */
export async function generatePDFReport(
  analysis: Analysis,
  scan: Scan,
  previousAnalyses: Analysis[] = [],
  userName: string = 'Patient',
): Promise<Blob> {
  try {
    const isLongitudinal = analysis.analysis_type === 'longitudinal' && previousAnalyses.length > 0;
    const riskScorePercent = Math.round(analysis.risk_score);
    const classificationText = analysis.classification === 'suspicious' ? 'Suspicious' : 'Normal';
    const scanDate = new Date(scan.scan_date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const generationDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });

    // Create PDF document
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    let yPosition = margin;

    // Helper function to add header to each page
    const addHeader = () => {
      pdf.setFontSize(14);
      pdf.setTextColor(14, 165, 233); // Blue color
      pdf.text('PanEcho', margin, yPosition);
      pdf.setFontSize(10);
      pdf.setTextColor(107, 114, 128); // Gray color
      pdf.text('CT Scan Analysis Report', pageWidth - margin - 50, yPosition);
      yPosition += 8;

      // Add separator line
      pdf.setDrawColor(230, 233, 243); // Light blue
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;
    };

    // Helper function to add footer with disclaimer
    const addFooter = () => {
      pdf.setFontSize(8);
      pdf.setTextColor(153, 27, 27); // Red
      pdf.text('Not a diagnostic tool - consult a physician', margin, pageHeight - 12);
      pdf.setFontSize(7);
      pdf.setTextColor(107, 114, 128);
      pdf.text(`Generated by PanEcho on ${generationDate}`, margin, pageHeight - 7);
    };

    // Helper function to add page number
    const addPageNumber = (pageNum: number, totalPages: number) => {
      pdf.setFontSize(8);
      pdf.setTextColor(107, 114, 128);
      pdf.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin - 15, pageHeight - 7);
    };

    // PAGE 1: SUMMARY
    addHeader();

    pdf.setFontSize(18);
    pdf.setTextColor(17, 24, 39); // Dark color
    pdf.text('Clinical Summary', margin, yPosition);
    yPosition += 10;

    // Patient information
    pdf.setFontSize(11);
    pdf.setTextColor(31, 41, 55);
    pdf.text('Patient Information', margin, yPosition);
    yPosition += 6;

    pdf.setFontSize(10);
    pdf.setTextColor(107, 114, 128);
    const patientInfo = [
      `Patient Name: ${userName}`,
      `Scan Date: ${scanDate}`,
      `Age: ${analysis.detailed_findings?.age || 'Not provided'}`,
      `Scan ID: ${scan.id}`,
    ];
    patientInfo.forEach((info) => {
      pdf.text(info, margin + 5, yPosition);
      yPosition += 5;
    });

    yPosition += 3;

    // Classification and Risk Score box
    pdf.setFillColor(249, 250, 251); // Light gray background
    pdf.rect(margin, yPosition, pageWidth - 2 * margin, 20, 'F');
    pdf.setFontSize(11);
    pdf.setTextColor(31, 41, 55);
    pdf.text('Classification', margin + 5, yPosition + 5);
    pdf.setFontSize(10);
    pdf.setTextColor(107, 114, 128);
    pdf.text(classificationText, margin + 5, yPosition + 10);

    pdf.setFontSize(11);
    pdf.setTextColor(31, 41, 55);
    pdf.text('Risk Score', pageWidth / 2 + 5, yPosition + 5);
    pdf.setFontSize(16);
    pdf.setTextColor(14, 165, 233); // Blue
    pdf.text(`${riskScorePercent}%`, pageWidth / 2 + 5, yPosition + 13);

    yPosition += 25;

    // AI Summary
    pdf.setFontSize(11);
    pdf.setTextColor(31, 41, 55);
    pdf.text('Clinical Summary', margin, yPosition);
    yPosition += 6;

    pdf.setFontSize(10);
    pdf.setTextColor(107, 114, 128);
    const summaryLines = pdf.splitTextToSize(analysis.ai_summary, pageWidth - 2 * margin - 10);
    pdf.text(summaryLines, margin + 5, yPosition);
    yPosition += summaryLines.length * 5 + 5;

    // Key Findings
    if (analysis.detailed_findings?.radiomic_features && analysis.detailed_findings.radiomic_features.length > 0) {
      pdf.setFontSize(11);
      pdf.setTextColor(31, 41, 55);
      pdf.text('Key Findings', margin, yPosition);
      yPosition += 6;

      pdf.setFontSize(10);
      pdf.setTextColor(107, 114, 128);
      analysis.detailed_findings.radiomic_features.slice(0, 5).forEach((feature: string) => {
        pdf.text(`• ${feature}`, margin + 5, yPosition);
        yPosition += 5;
      });
      yPosition += 3;
    }

    // DISCLAIMER - PROMINENT
    pdf.setFillColor(254, 242, 242); // Red background
    pdf.setDrawColor(153, 27, 27); // Red border
    pdf.rect(margin, yPosition, pageWidth - 2 * margin, 25, 'FD');

    pdf.setFontSize(11);
    pdf.setTextColor(153, 27, 27);
    pdf.text('⚠ DISCLAIMER', margin + 5, yPosition + 5);

    pdf.setFontSize(9);
    pdf.setTextColor(153, 27, 27);
    const disclaimerText =
      'This analysis is generated by artificial intelligence and is NOT a diagnostic tool. ' +
      'It should not be used as the sole basis for clinical decision-making. ' +
      'Always consult with a qualified physician.';
    const disclaimerLines = pdf.splitTextToSize(disclaimerText, pageWidth - 2 * margin - 10);
    pdf.text(disclaimerLines, margin + 5, yPosition + 10);

    addFooter();
    addPageNumber(1, isLongitudinal ? 4 : 3);

    // PAGE 2: DETAILED FINDINGS
    if (analysis.detailed_findings) {
      pdf.addPage();
      yPosition = margin;
      addHeader();

      pdf.setFontSize(18);
      pdf.setTextColor(17, 24, 39);
      pdf.text('Detailed Findings', margin, yPosition);
      yPosition += 10;

      // Radiomic Features
      if (analysis.detailed_findings.radiomic_features && analysis.detailed_findings.radiomic_features.length > 0) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Radiomic Features', margin, yPosition);
        yPosition += 6;

        pdf.setFontSize(10);
        pdf.setTextColor(107, 114, 128);
        analysis.detailed_findings.radiomic_features.forEach((feature: string) => {
          pdf.text(`• ${feature}`, margin + 5, yPosition);
          yPosition += 5;
          if (yPosition > pageHeight - 30) {
            pdf.addPage();
            yPosition = margin;
            addHeader();
          }
        });
        yPosition += 3;
      }

      // Areas of Concern
      if (
        analysis.detailed_findings.areas_of_concern &&
        analysis.detailed_findings.areas_of_concern.length > 0
      ) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Areas of Concern', margin, yPosition);
        yPosition += 6;

        analysis.detailed_findings.areas_of_concern.forEach((area: any) => {
          pdf.setFillColor(249, 250, 251);
          pdf.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');

          pdf.setFontSize(10);
          pdf.setTextColor(31, 41, 55);
          pdf.text(area.location, margin + 5, yPosition + 5);

          pdf.setFontSize(9);
          pdf.setTextColor(107, 114, 128);
          pdf.text(area.description, margin + 5, yPosition + 10);

          if (area.slice_numbers) {
            pdf.setFontSize(8);
            pdf.text(`Slices: ${area.slice_numbers.join(', ')}`, margin + 5, yPosition + 13);
          }

          yPosition += 18;
          if (yPosition > pageHeight - 30) {
            pdf.addPage();
            yPosition = margin;
            addHeader();
          }
        });
      }

      // Measurements Table
      if (analysis.detailed_findings.measurements && Object.keys(analysis.detailed_findings.measurements).length > 0) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Measurements', margin, yPosition);
        yPosition += 8;

        pdf.setFontSize(9);
        pdf.setTextColor(17, 24, 39);

        // Table headers
        pdf.setFillColor(243, 244, 246);
        pdf.rect(margin, yPosition - 3, (pageWidth - 2 * margin) / 2, 5, 'F');
        pdf.rect(margin + (pageWidth - 2 * margin) / 2, yPosition - 3, (pageWidth - 2 * margin) / 2, 5, 'F');

        pdf.text('Parameter', margin + 3, yPosition);
        pdf.text('Value', margin + (pageWidth - 2 * margin) / 2 + 3, yPosition);
        yPosition += 7;

        pdf.setTextColor(107, 114, 128);
        Object.entries(analysis.detailed_findings.measurements).forEach(([key, value]) => {
          pdf.text(key, margin + 3, yPosition);
          pdf.text(String(value), margin + (pageWidth - 2 * margin) / 2 + 3, yPosition);
          yPosition += 5;
          if (yPosition > pageHeight - 30) {
            pdf.addPage();
            yPosition = margin;
            addHeader();
          }
        });
      }

      addFooter();
      addPageNumber(2, isLongitudinal ? 4 : 3);
    }

    // PAGE 3: LONGITUDINAL (if applicable)
    if (isLongitudinal) {
      pdf.addPage();
      yPosition = margin;
      addHeader();

      pdf.setFontSize(18);
      pdf.setTextColor(17, 24, 39);
      pdf.text('Longitudinal Comparison', margin, yPosition);
      yPosition += 10;

      // Risk Score Progression Table
      pdf.setFontSize(11);
      pdf.setTextColor(31, 41, 55);
      pdf.text('Risk Score Progression', margin, yPosition);
      yPosition += 8;

      pdf.setFontSize(9);
      pdf.setTextColor(17, 24, 39);

      // Table headers
      pdf.setFillColor(243, 244, 246);
      const colWidth = (pageWidth - 2 * margin) / 3;
      pdf.rect(margin, yPosition - 3, colWidth, 5, 'F');
      pdf.rect(margin + colWidth, yPosition - 3, colWidth, 5, 'F');
      pdf.rect(margin + 2 * colWidth, yPosition - 3, colWidth, 5, 'F');

      pdf.text('Scan Date', margin + 3, yPosition);
      pdf.text('Risk Score', margin + colWidth + 3, yPosition);
      pdf.text('Classification', margin + 2 * colWidth + 3, yPosition);
      yPosition += 7;

      pdf.setTextColor(107, 114, 128);
      const recentAnalyses = previousAnalyses.slice(-3);
      recentAnalyses.forEach((prev) => {
        const prevDate = new Date(prev.created_at).toLocaleDateString('en-US', {
          month: 'short',
          day: 'numeric',
          year: '2-digit',
        });
        pdf.text(prevDate, margin + 3, yPosition);
        pdf.text(`${Math.round(prev.risk_score)}%`, margin + colWidth + 3, yPosition);
        pdf.text(prev.classification, margin + 2 * colWidth + 3, yPosition);
        yPosition += 5;
      });

      // Current scan
      const currentDate = new Date(analysis.created_at).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: '2-digit',
      });
      pdf.setTextColor(14, 165, 233); // Highlight current
      pdf.text(currentDate, margin + 3, yPosition);
      pdf.text(`${riskScorePercent}%`, margin + colWidth + 3, yPosition);
      pdf.text(analysis.classification, margin + 2 * colWidth + 3, yPosition);
      yPosition += 8;

      // Comparison Results
      if (analysis.detailed_findings?.comparison_results) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Comparison to Previous Scan', margin, yPosition);
        yPosition += 6;

        if (analysis.detailed_findings.comparison_results.size_changes && 
            analysis.detailed_findings.comparison_results.size_changes.length > 0) {
          pdf.setFontSize(10);
          pdf.setTextColor(31, 41, 55);
          pdf.text('Size Changes', margin + 5, yPosition);
          yPosition += 4;

          pdf.setFontSize(9);
          pdf.setTextColor(107, 114, 128);
          analysis.detailed_findings.comparison_results.size_changes.forEach((change: any) => {
            const changeText = `${change.finding}: ${change.direction} by ${change.magnitude}`;
            pdf.text(changeText, margin + 10, yPosition);
            yPosition += 4;
          });
        }
      }

      // Trajectory Assessment
      if (analysis.detailed_findings?.trajectory_results) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Trajectory Assessment', margin, yPosition);
        yPosition += 6;

        pdf.setFontSize(9);
        pdf.setTextColor(107, 114, 128);

        if (analysis.detailed_findings.trajectory_results.direction) {
          pdf.text(
            `Direction: ${analysis.detailed_findings.trajectory_results.direction}`,
            margin + 5,
            yPosition,
          );
          yPosition += 4;
        }
        if (analysis.detailed_findings.trajectory_results.rate) {
          pdf.text(`Rate: ${analysis.detailed_findings.trajectory_results.rate}`, margin + 5, yPosition);
          yPosition += 4;
        }
        if (analysis.detailed_findings.trajectory_results.clinical_significance) {
          const sigLines = pdf.splitTextToSize(
            `Significance: ${analysis.detailed_findings.trajectory_results.clinical_significance}`,
            pageWidth - 2 * margin - 10,
          );
          pdf.text(sigLines, margin + 5, yPosition);
          yPosition += sigLines.length * 4;
        }
      }

      addFooter();
      addPageNumber(3, 4);
    }

    // PAGE 4 (or 3): CLINICAL CONTEXT
    pdf.addPage();
    yPosition = margin;
    addHeader();

    pdf.setFontSize(18);
    pdf.setTextColor(17, 24, 39);
    pdf.text('Clinical Context & Recommendations', margin, yPosition);
    yPosition += 10;

    // Clinical Information
    if (analysis.detailed_findings) {
      pdf.setFontSize(11);
      pdf.setTextColor(31, 41, 55);
      pdf.text('Clinical Information', margin, yPosition);
      yPosition += 6;

      pdf.setFontSize(10);
      pdf.setTextColor(31, 41, 55);

      if (analysis.detailed_findings.symptoms) {
        pdf.text('Reported Symptoms:', margin + 5, yPosition);
        yPosition += 4;
        pdf.setFontSize(9);
        pdf.setTextColor(107, 114, 128);
        pdf.text(analysis.detailed_findings.symptoms || 'None reported', margin + 10, yPosition);
        yPosition += 5;
      }

      if (analysis.detailed_findings.family_history) {
        pdf.setFontSize(10);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Family History:', margin + 5, yPosition);
        yPosition += 4;
        pdf.setFontSize(9);
        pdf.setTextColor(107, 114, 128);
        pdf.text(analysis.detailed_findings.family_history, margin + 10, yPosition);
        yPosition += 5;
      }

      if (analysis.detailed_findings.previous_conditions) {
        pdf.setFontSize(10);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Previous Conditions:', margin + 5, yPosition);
        yPosition += 4;
        pdf.setFontSize(9);
        pdf.setTextColor(107, 114, 128);
        const conditions = Array.isArray(analysis.detailed_findings.previous_conditions)
          ? analysis.detailed_findings.previous_conditions.join(', ')
          : analysis.detailed_findings.previous_conditions;
        pdf.text(conditions, margin + 10, yPosition);
        yPosition += 5;
      }

      yPosition += 3;

      // Recommendations
      if (analysis.detailed_findings.recommendations && analysis.detailed_findings.recommendations.length > 0) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Clinical Recommendations', margin, yPosition);
        yPosition += 6;

        pdf.setFontSize(9);
        pdf.setTextColor(107, 114, 128);
        analysis.detailed_findings.recommendations.forEach((rec) => {
          pdf.text(`• ${rec}`, margin + 5, yPosition);
          yPosition += 4;
          if (yPosition > pageHeight - 30) {
            pdf.addPage();
            yPosition = margin;
            addHeader();
          }
        });
      }

      yPosition += 3;

      // Follow-up Guidance
      if (analysis.detailed_findings.trajectory_results?.follow_up_recommendation) {
        pdf.setFontSize(11);
        pdf.setTextColor(31, 41, 55);
        pdf.text('Follow-up Guidance', margin, yPosition);
        yPosition += 6;

        pdf.setFontSize(10);
        pdf.setTextColor(107, 114, 128);
        const followUpLines = pdf.splitTextToSize(
          analysis.detailed_findings.trajectory_results.follow_up_recommendation,
          pageWidth - 2 * margin - 10,
        );
        pdf.text(followUpLines, margin + 5, yPosition);
        yPosition += followUpLines.length * 4 + 5;
      }
    }

    // Final Disclaimer
    pdf.setFillColor(254, 242, 242);
    pdf.setDrawColor(153, 27, 27);
    pdf.rect(margin, yPosition, pageWidth - 2 * margin, 25, 'FD');

    pdf.setFontSize(10);
    pdf.setTextColor(153, 27, 27);
    pdf.text('⚠ IMPORTANT NOTICE', margin + 5, yPosition + 5);

    pdf.setFontSize(8);
    const importantText =
      'This report is generated by artificial intelligence and is NOT intended to replace ' +
      'professional medical judgment. Clinical decisions should be made by qualified medical professionals.';
    const importantLines = pdf.splitTextToSize(importantText, pageWidth - 2 * margin - 10);
    pdf.text(importantLines, margin + 5, yPosition + 10);

    addFooter();
    addPageNumber(isLongitudinal ? 4 : 3, isLongitudinal ? 4 : 3);

    // Convert to blob
    const blob = pdf.output('blob');
    return blob;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
}

/**
 * Generate filename for PDF report
 * @param userName - User's name
 * @param scanDate - Date of scan
 * @returns Formatted filename
 */
export function generatePDFFilename(userName: string, scanDate: Date): string {
  const dateStr = scanDate.toISOString().split('T')[0]; // YYYY-MM-DD
  const cleanName = userName.replace(/[^a-zA-Z0-9]/g, '_');
  return `PanEcho_Report_${cleanName}_${dateStr}.pdf`;
}
